services:

  blazor.server:
    image: ghcr.io/saifdevopz/blazor-server:latest
    container_name: blazor-server
    build:
      context: ../
      dockerfile: src/apps/Blazor.Server/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5050:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.blazor-server.loadbalancer.server.port=8080"
      - "traefik.http.routers.blazor-server.entrypoints=https"
      - "traefik.http.routers.blazor-server.rule=Host(`blazor.webport.co.za`)"
      - "traefik.http.routers.blazor-server.tls=true"
      - "traefik.http.routers.blazor-server.tls.certresolver=cloudflare"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
    networks:
      - proxy

networks:
  proxy:
    external: true