services:

  system.api:
    image: ghcr.io/saifdevopz/system-api:latest
    container_name: system-api
    build:
      context: .
      dockerfile: src/api/System.API/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5000:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.parent-api.loadbalancer.server.port=8080"
      - "traefik.http.routers.parent-api.entrypoints=https"
      - "traefik.http.routers.parent-api.rule=Host(`system.webport.co.za`)"
      - "traefik.http.routers.parent-api.tls=true"
      - "traefik.http.routers.parent-api.tls.certresolver=cloudflare"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
    networks:
      - proxy

networks:
  proxy:
    external: true