name: Blazor.Server CI/CD

on:
  #push:
    #branches:
      #- master
  workflow_dispatch:

jobs:
  build_images:
    name: Package Software
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and Push Docker Image using Compose with Buildx
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/blazor-server
          TAG=$(echo $GITHUB_SHA | cut -c1-7)
          
          docker compose -f docker-compose-blazor-server.yml build \
            --builder default \
            --progress plain \
            --build-arg BUILDKIT_INLINE_CACHE=1
          
          docker compose -f docker-compose-blazor-server.yml push

  copy_files:
    name: Copy files to server
    runs-on: ubuntu-latest
    needs: build_images
    steps:
      - uses: actions/checkout@v4
      - name: Copy file via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: docker-compose-blazor-server.yml
          target: /root/webport-system

  update_server:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: copy_files
    steps:
      - name: Replacing container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/webport-system
            docker-compose -f docker-compose-blazor-server.yml down || true
            docker image prune -a -f
            docker-compose pull
            docker-compose -f docker-compose-blazor-server.yml up -d
